# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef99f0865e7aeae0ac3fd1977c5a77b33ab0a39cca62b1d85d6d452ad3d70362f0250d4ab1aa58d1e50afb9e40f7a5f9fd90ae414917d68840aa05e7b241dc73

test:
  secret_key_base: 0baf2831fdced6418ca477feaf222b96a5ffc4556ea0383f2166f57e09139b7b20f7898a8b3a86d9e929be7cf7acd516b1296a0ac5c0d5e01459fb1952a8f496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
